server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: route_service_one
        uri: http://localhost:8081
        predicates:
        - Path=/api/**
        filters:
        - StripPrefix=1 # 表示在转发时去掉api